yatube/about/urls.py
from django.urls import path
from . import views


app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug:slug>/', views.group_posts, name='group_list'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('create/', views.post_create, name='post_create'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    path('posts/<int:post_id>/comment/', views.add_comment,
         name='add_comment'),
    path('follow/', views.follow_index, name='follow_index'),
    path(
        'profile/<str:username>/follow/',
        views.profile_follow,
        name='profile_follow'
    ),
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name='profile_unfollow'
    ),
]

yatube/yatube/urls.py
from django.contrib import admin

from django.urls import include, path

from django.conf import settings
from django.conf.urls.static import static

handler404 = 'core.views.page_not_found'
handler403 = 'core.views.permission_denied'

urlpatterns = [
    path('', include('posts.urls', namespace='posts')),
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
]
if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/posts/models.py
from django.db import models
from core.models import CreatedModel

from django.contrib.auth import get_user_model

User = get_user_model()

POST_TEXT_LIMIT = 15


class Group(models.Model):
    title = models.CharField(
        max_length=200,
        verbose_name='Название группы',
    )
    slug = models.SlugField(unique=True)
    description = models.TextField(
        null=True,
        verbose_name='Описание группы',
        help_text="Опишите группу",
    )

    class Meta:
        default_related_name = 'posts'
        verbose_name = 'Группа'
        verbose_name_plural = 'Группы'

    def __str__(self):
        return self.title


class Post(models.Model):
    text = models.TextField(
        verbose_name='Текст поста',
        help_text="Введите текст поста"
    )
    pub_date = models.DateTimeField(
        verbose_name='Дата публикации',
        auto_now_add=True,
        db_index=True
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        verbose_name='Автор'
    )
    group = models.ForeignKey(
        Group,
        on_delete=models.SET_NULL,
        blank=True,
        null=True,
        verbose_name='Группа',
        help_text='Группа, к которой будет относиться пост'
    )

    image = models.ImageField(
        verbose_name='Картинка',
        upload_to='posts/',
        blank=True
    )

    class Meta:
        ordering = ['-pub_date']
        default_related_name = 'posts'
        verbose_name = 'Пост'
        verbose_name_plural = 'Посты'

    def __str__(self):
        return self.text[:POST_TEXT_LIMIT]


class Comment(CreatedModel):
    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
        verbose_name='Пост'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        verbose_name='Автор'
    )
    text = models.TextField(
        verbose_name='Текст комментария',
        help_text="Введите текст"
    )
    created = models.DateTimeField(
        verbose_name='Дата публикации комментария',
        auto_now_add=True,
    )

    class Meta:
        default_related_name = 'comments'
        verbose_name = 'Комментарий'
        verbose_name_plural = 'Комментарии'

    def __str__(self):
        return self.text[:POST_TEXT_LIMIT]


class Follow(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='follower',
        verbose_name='Пользователь',
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='following',
        verbose_name='Автор',
    )

    class Meta:
        verbose_name = 'Подписчик',
        verbose_name_plural = 'Автор'

    def __str__(self):
        return f'{self.user} подписался на {self.author}'

yatube/posts/forms.py
from django import forms

from .models import Post, Comment


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('group', 'text', 'image')


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('text',)

yatube/posts/views.py
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.views.decorators.cache import cache_page
from django.shortcuts import render, get_object_or_404
from django.shortcuts import redirect
from django.conf import settings

from posts.models import Post, Group, Follow, User
from posts.forms import PostForm, CommentForm


def get_paginator(request, posts, posts_per_page):
    paginator = Paginator(posts, posts_per_page)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    return page_obj


@cache_page(20, key_prefix='/')
def index(request):
    posts = Post.objects.all()
    page_obj = get_paginator(request, posts, settings.MAX_NUMBER_POST)
    context = {
        'page_obj': page_obj,
    }
    return render(request, 'posts/index.html', context)


def group_posts(request, slug):
    group = get_object_or_404(Group, slug=slug)
    posts = group.posts.select_related('author', 'group')
    page_obj = get_paginator(request, posts, settings.MAX_NUMBER_POST)
    context = {
        'page_obj': page_obj,
        'group': group,
    }
    return render(request, 'posts/group_list.html', context)


def profile(request, username):
    author = get_object_or_404(User, username=username)
    posts = author.posts.all()
    page_obj = get_paginator(request, posts, settings.MAX_NUMBER_POST)
    following = request.user.is_authenticated
    if following:
        following = author.following.filter(user=request.user).exists()
    context = {
        'page_obj': page_obj,
        'author': author,
        'following': following,
    }
    return render(request, 'posts/profile.html', context)


def post_detail(request, post_id):
    post = get_object_or_404(Post.objects.select_related('author', 'group'),
                             pk=post_id)
    comments = post.comments.select_related('post')
    form = CommentForm(request.POST or None)
    context = {
        'post': post,
        'form': form,
        'comments': comments,
    }
    return render(request, 'posts/post_detail.html', context)


@login_required
def post_create(request):
    is_edit = False
    form = PostForm(request.POST or None)

    if form.is_valid():
        post = form.save(commit=False)
        post.author = request.user
        post.save()

        return redirect('posts:profile', post.author.username)

    context = {
        'form': form,
        'is_edit': is_edit,
    }

    return render(request, 'posts/create_post.html', context)


@login_required
def post_edit(request, post_id):
    post = get_object_or_404(Post, pk=post_id)

    if post.author != request.user:
        return redirect('posts:post_detail', post_id=post_id)

    form = PostForm(
        request.POST or None,
        files=request.FILES or None,
        instance=post
    )

    if form.is_valid():
        form.save()
        return redirect('posts:post_detail', post_id=post_id)

    context = {
        'form': form,
        'is_edit': True,
    }

    return render(request, 'posts/create_post.html', context)


@login_required
def add_comment(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
    return redirect('posts:post_detail', post_id=post_id)


@login_required
def follow_index(request):
    posts = Post.objects.filter(
        author__following__user=request.user)
    page_obj = get_paginator(request, posts, settings.MAX_NUMBER_POST)
    context = {
        'page_obj': page_obj,
    }
    return render(request, 'posts/follow.html', context)


@login_required
def profile_follow(request, username):
    author = get_object_or_404(User, username=username)
    if request.user == author:
        return redirect('posts:follow_index')
    Follow.objects.get_or_create(
        user=request.user,
        author=author,
    )
    return redirect('posts:profile', username=username)


@login_required
def profile_unfollow(request, username):
    follower = get_object_or_404(
        Follow,
        user=request.user,
        author__username=username
    )
    follower.delete()
    return redirect('posts:profile', username)

yatube/templates/posts/create_post.html
{% extends 'base.html' %}
{% load static %}

{% block title%}
  {% include 'posts/includes/post_edit.html' %}
{% endblock %}
{% block content %}
  <div class="container py-5">
      <div class="row justify-content-center">
        <div class="col-md-8 p-5">
          <div class="card">
            <div class="card-header">
              {% include 'posts/includes/post_edit.html' %}           
            </div>
              {% include 'posts/includes/form_field.html' %}
              <form method="post" action="{% url 'posts:post_create' %}">
                {% csrf_token %}
                {{ form.as_p }}                  
                {% if is_edit %}           
                  <button type="submit" class="btn btn-primary">
                    Сохранить
                  </button>
                {% else %}
                  <button type="submit" class="btn btn-primary">
                    Добавить
                  </button>
                {% endif %}
                </button> 
                <form method="post" enctype="multipart/form-data">
                  {% csrf_token %}
                  {% for field in form %}
                  {% endfor %}       
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
{% endblock%}

yatube/templates/posts/follow.html
{% extends 'base.html' %}

{% block H1%}
  <h1>Обновления авторов на которых вы подписаны</h1>
{% endblock%}
{% block content %}
  {% include 'posts/includes/switcher.html' %}  
  {% for post in page_obj %}
      {% include 'includes/author_date.html' %}    
      {% if post.group %}
        <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a> 
      {% endif %}
    {% if not forloop.last %}<hr>{% endif %}
  {% endfor %}
  {% include 'posts/includes/paginator.html' %}
{% endblock %}

yatube/templates/posts/group_list.html
{% extends 'base.html' %}

{% block content %}
<h1>{{ group.title }}</h1>
  <p>
    {{ group.description|linebreaksbr }}
  </p>
  {% for post in page_obj %}
    {% include 'includes/author_date.html' %}   
    {% if not forloop.last %}<hr>{% endif %}        
  {% endfor %} 
  {% include 'posts/includes/paginator.html' %}        
{% endblock %} 

yatube/templates/posts/index.html
{% extends 'base.html' %}

{% block H1%}
  <h1>Последние обновления на сайте</h1>
{% endblock%}
{% block content %}
  {% include 'posts/includes/switcher.html' %}
  {% for post in page_obj %}
      {% include 'includes/author_date.html' %}     
      {% if post.group %}
        <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a> 
      {% endif %}
    {% if not forloop.last %}<hr>{% endif %}
  {% endfor %}
  {% include 'posts/includes/paginator.html' %}
{% endblock %}

yatube/templates/posts/post_detail.html
{% extends 'base.html' %}
{% load thumbnail %}

{% block H1%}
  <h1>Пост {{ post|slice:":30" }}</h1>
{% endblock%}
{% block content %} 
      <div class="row">
        <aside class="col-12 col-md-3">
          <ul class="list-group list-group-flush">
            <li class="list-group-item">
              Дата публикации: {{ post.pub_date|date:"d E Y" }}
            </li>   
            <li class="list-group-item">
              {% if post.group %}
              Группа: {{ post.group.title }}
                <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
              {% endif %}  
            </li>
            <li class="list-group-item">
              Автор: {{ post.author.get_full_name }}
            </li>
            <li class="list-group-item d-flex justify-content-between align-items-center">
              Всего постов автора:  <span >{{ posts.author.posts.count }}</span>
            </li>
            <li class="list-group-item">
              <a href="{% url 'posts:profile' post.author.username %}">
                все посты пользователя
              </a>
            </li>
          </ul>
        </aside>
        <article class="col-12 col-md-9">
          {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
            <img class="card-img my-2" src="{{ im.url }}">
          {% endthumbnail %}
          <p>
            {{ post.text|safe }}
          </p>
          {% if user.is_authenticated and user == post.author%}
            <a class="btn btn-primary" href="{% url 'posts:post_edit' post.id %}">
              редактировать запись
            </a>    
          {% endif %} 
         {% include 'posts/includes/comment.html' %}          
        </article>
      </div> 
{% endblock %}

yatube/templates/posts/profile.html
{% extends 'base.html' %}

{% block H1%}
  <h1>Профайл пользователя {{ post.author.get_full_name }}</h1>
{% endblock%}
{% block content %}
    <div class="mb-5">
     <h1>Все посты пользователя {{ author.get_full_name }} </h1>
     <h3>Всего постов: {{ author.posts.count }} </h3> 
     {% include 'posts/includes/form_follow.html' %}
    </div> 
    {% for post in page_obj %}
    <a href="{% url 'posts:post_detail' post.id %}">подробная информация </a>
  </article>
  {% if post.group %}
    <a href="{% url 'posts:group_list' post.group.slug %}">
    все записи группы
  </a>
  {% endif %}       
  <hr> 
    {% endfor %} 
  {% if not forloop.last %}<hr>{% endif %}
  {% include 'posts/includes/paginator.html' %}  
{% endblock content %}